version: '3.0'
services:
  fuseki:
    command: [ "--tdb2", "--update", "--loc", "databases/DB2", "/ds" ]
    build:
      context: .
      dockerfile: Dockerfile
    image: fuseki
    hostname: disco-kg
    ports:
      - "3030:3030"
    volumes:
      - kg_dev_logs:/fuseki/logs
      - kg_dev_db:/fuseki/databases
    networks:
      - disco-graph-dev
networks:
  disco-graph-dev:
    name: disco-graph-dev
    external: true
volumes:
  kg_dev_logs:
  kg_dev_db: