version: '3.0'
services:
  fuseki:
    command: [ "--tdb2", "--update", "--loc", "databases/DB2", "/ds" ]
    build:
      context: .
      dockerfile: Dockerfile
    image: fuseki
    hostname: disco-kg
    volumes:
      - kg_logs:/fuseki/logs
      - kg_db:/fuseki/databases
    networks:
      - disco-graph

networks:
  disco-graph:
    name: disco-graph
    external: true
volumes:
  kg_logs:
  kg_db:
