version: "3.9"
services:
  graph-connector:
    hostname: graph-connector
    image: graph-connector:latest
    volumes:
      - ./dev_db:/home/graph-connector/instance
      - ./gunicorn.conf.py:/home/conf/gunicorn.conf.py
      - ./gunicorn-logging.conf:/home/conf/gunicorn-logging.conf
    environment:
      - SECRET_TOKEN=debug
    ports:
      - "5000:5000"