version: "3.9"
services:
  graph-connector:
    hostname: graph-connector
    image: graph-connector:latest
    volumes:
      - ./db:/home/graph-connector/instance
      - ./gunicorn.conf.py:/home/conf/gunicorn.conf.py
      - ./gunicorn-logging.conf:/home/conf/gunicorn-logging.conf
    environment:
      - SECRET_TOKEN=change_to_secure_token
    networks:
      - disco-graph
networks:
  disco-graph:
    name: disco-graph
    external: true