version: "3.9"
services:
  ui:
    hostname: disco-ui
    image: disco-graph-ui:latest
    ports:
      - "4200:80"
    networks:
      - disco-graph-dev
networks:
  disco-graph-dev:
    name: disco-graph-dev
    external: true